### ISSUE TITLE
test-infra-cleanup-GKE has URL template errors

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#1504]
```yaml
jsonPayload: {
  component:  "plank"   
  file:  "prow/pjutil/pjutil.go:275"   
  func:  "k8s.io/test-infra/prow/pjutil.JobURL"   
  job:  "test-infra-cleanup-GKE"   
  level:  "error"   
  msg:  "error executing URL template: template: JobURL:1:192: executing "JobURL" at <.Spec.Type>: Type has arguments but cannot be invoked as function"   
  name:  "fd7afd7c-a8f8-11e9-8439-42993ba28a37"   
  type:  "periodic"   
 }
```

FYI @katharine
