### ISSUE TITLE
tide sync errors

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#1505]
```yaml
jsonPayload: {
  component:  "tide"   
  error:  "sleep time for token reset exceeds max sleep time (3m50.784736403s > 2m0s)"   
  file:  "prow/cmd/tide/main.go:208"   
  func:  "main.sync"   
  level:  "error"   
  msg:  "Error syncing."   
 }
```

/assign @cjwagner 

What is the result of it and any ideas how we can avoid it?
