### ISSUE TITLE
Create a periodic job to update istio.io reference docs

### ISSUE THREAD

**Issue by geeknoid** [istio/test-infra#1626]
We need a nightly job that updates istio.io's reference docs. To do this, the job needs to check out the istio/istio.io repo and run the scripts/grab_reference_docs.sh script. If after running the script any files are modified in the repo, create a PR for the changes.

This only needs to work on the master branch.

**Comment by scottilee** [comment]
@geeknoid I wanted to take a shot at this. Does this look like a good start?

```
- interval: 24h
  name: istioio-update-periodic
  branches: master
  decorate: true
  annotations:
    testgrid-dashboards: istio_istio.io
    testgrid-alert-email: istio-oncall@googlegroups.com
    testgrid-num-failures-to-alert: '1'
  labels:
    preset-release-pipeline: "true"
  branches: master
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/istio-testing/prowbazel:0.4.13
      args:
      - "--repo=github.com/istio/istio.io"
      - "--clean"
      - "--timeout=120"
      command:
        - ./scripts/grab_reference_docs.sh
      # Bazel needs privileged mode in order to sandbox builds.
      securityContext:
        privileged: true
    nodeSelector:
      testing: build-pool
```

Also, I wasn't sure about the whole looking for modified files and creating a PR part. Any examples of this somewhere?
