### ISSUE TITLE
linsun-patch-12 has required prow jobs but does not use protection

### ISSUE THREAD

**Issue by geeknoid** [istio/test-infra#1639]
@fejta commented on [Thu Aug 08 2019](https://github.com/istio/istio.io/issues/4775)

/assign @linsun @geeknoid 

```yaml
{
 insertId:  "ivd8rpg13r3fun"  
 jsonPayload: {
  component:  "branchprotector"   
  error:  "update istio: update istio.io: update linsun-patch-12 from protected=false: get policy: required prow jobs require branch protection"   
  file:  "prow/cmd/branchprotector/protect.go:127"   
  func:  "main.main"   
  level:  "error"   
  msg:  "0"   
 }
 labels: {…}  
 logName:  "projects/istio-testing/logs/branchprotector"  
 receiveTimestamp:  "2019-08-08T22:01:13.643393702Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-08-08T22:01:12Z"  
}
```

---

@geeknoid commented on [Fri Aug 09 2019](https://github.com/istio/istio.io/issues/4775#issuecomment-519881098)

This is related to https://github.com/istio/test-infra/issues/1511
