### ISSUE TITLE
need to sync tide state

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#1664]
/assign

```yaml
{
 insertId:  "9frp83g36b6agq"  
 jsonPayload: {
  component:  "tide"   
  error:  "query "is:pr state:open repo:\"istio-releases/pipeline\" -label:\"do-not-merge\" -label:\"do-not-merge/hold\" -label:\"do-not-merge/work-in-progress\" -label:\"needs-ok-to-test\" -label:\"needs-rebase\"", err: non-200 OK status code: 502 Bad Gateway body: "{\n   \"data\": null,\n   \"errors\":[\n      {\n         \"message\":\"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `90A8:401B:19A3:21D3:5D533B9C` when reporting this issue.\"\n      }\n   ]\n}\n""   
  file:  "prow/cmd/tide/main.go:208"   
  func:  "main.sync"   
  level:  "error"   
  msg:  "Error syncing."   
 }
 labels: {…}  
 logName:  "projects/istio-testing/logs/tide"  
 receiveTimestamp:  "2019-08-13T22:37:53.779971104Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-08-13T22:37:47Z"  
}
```

Most likely because this is querying too many PRs, DOSing our search quota. Can fix by saving a timestamp to GCS
