### ISSUE TITLE
deck does not have storage.objects.list access to istio-private-build

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#1856]
Any ideas about this @howardjohn @clarketm @geeknoid ?

```yaml
{
 insertId: "12um6rvg1r5m1t9"  
 jsonPayload: {
  component: "deck"   
  error: "googleapi: Error 401: Anonymous caller does not have storage.objects.list access to istio-private-build., required"   
  file: "prow/spyglass/gcsartifact_fetcher.go:133"   
  func: "k8s.io/test-infra/prow/spyglass.(*GCSArtifactFetcher).artifacts"   
  jobPrefix: "istio-private-build/logs/istio-private-build_postsubmit/3/"   
  level: "error"   
  msg: "Error accessing GCS artifact."   
 }
 labels: {…}  
 logName: "projects/istio-testing/logs/deck"  
 receiveTimestamp: "2019-09-27T22:02:23.705047539Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-09-27T22:02:17Z"  
}
```

We should either a) give prow this access or more likely b) remove these jobs from the default deck display

/kind oncall-hotlist
