### ISSUE TITLE
Remove deprecated elide_skipped_contexts field

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#1858]
```yaml
 jsonPayload: {
  level: "warning"   
  msg: "elide_skipped_contexts is deprecated and will be removed after Oct. 2019. Skipped contexts are now elided by default."   
 }
```
