### ISSUE TITLE
replace default_decoration_config with default_decoration_configs

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#1921]
ref https://github.com/kubernetes/test-infra/issues/14682

```yaml
{
 insertId: "1wjgoq4g3r9vekz"  
 jsonPayload: {
  component: "hook"   
  file: "prow/config/config.go:930"   
  func: "k8s.io/test-infra/prow/config.(*Config).finalizeJobConfig"   
  level: "warning"   
  msg: "default_decoration_config will be deprecated on April 2020, and it will be replaced with default_decoration_configs['*']."   
 }
 labels: {…}  
 logName: "projects/istio-testing/logs/hook"  
 receiveTimestamp: "2019-10-09T22:07:08.081052530Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-09T22:06:14Z"  
}
```

/kind oncall-hotlist
