### ISSUE TITLE
status-reconciler is not using ghproxy

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#2688]
```yaml

{
 insertId: "ut0w8kg1syq6ol"  
 jsonPayload: {
  component: "status-reconciler"   
  file: "prow/flagutil/github.go:78"   
  func: "k8s.io/test-infra/prow/flagutil.(*GitHubOptions).Validate"   
  level: "warning"   
  msg: "It doesn't look like you are using ghproxy to cache API calls to GitHub! This has become a required component of Prow and other components will soon be allowed to add features that may rapidly consume API ratelimit without caching. Starting May 1, 2020 use Prow components without ghproxy at your own risk! https://github.com/kubernetes/test-infra/tree/master/ghproxy#ghproxy"   
 }
 labels: {…}  
 logName: "projects/istio-testing/logs/statusreconciler"  
 receiveTimestamp: "2020-06-01T20:36:33.247075434Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2020-06-01T20:35:36Z"  
}
```
/kind oncall-hotlist
/assign
