### ISSUE TITLE
Migrate to --blob-storage-workers

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#2689]
/kind oncall-hotlist
/assign

```yaml
{
 insertId: "1ame69ng919eyvl"  
 jsonPayload: {
  component: "crier"   
  file: "prow/cmd/crier/main.go:125"   
  func: "main.(*options).validate"   
  level: "warning"   
  msg: "--gcs-workers is deprecated and will be removed in August 2020. Use --blob-storage-workers instead."   
 }
 labels: {…}  
 logName: "projects/istio-testing/logs/crier"  
 receiveTimestamp: "2020-06-01T20:36:47.616650973Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2020-06-01T20:35:44Z"  
}
```
